version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${DATABASE_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  api: 
    build: .
    volumes:
    - .:/app
    # - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb
  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to api:${APP_PORT}/subscriptions/stripe/webhook"
    env_file:
      - .env
volumes:
  mongodb_data_container: