version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  checkout:
    working_directory: ~/nest-boilerplate
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - checkout
      - save_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nest-boilerplate
  dependencies:
    working_directory: ~/nest-boilerplate
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/nest-boilerplate/node_modules
  lint:
    working_directory: ~/nest-boilerplate
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Prettier
          command: npm run format
  unit_test:
    working_directory: ~/nest-boilerplate
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
  integration_test:
    working_directory: ~/nest-boilerplate
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Copy .env
          command: cp .env.example .env
      - run:
          name: Run Docker API Build
          command: docker compose build api
      - run:
          name: Run seeds
          command: docker compose exec api npm run seed:run
      - run:
          name: Run start
          background: true
          command: docker compose up
      - run:
          name: Wait port
          command: sleep 20 && docker compose exec api node test/wait-on.js
      - run:
          name: Integration E2E test
          command: docker compose exec api npm run test:e2e
  build:
    working_directory: ~/nest-boilerplate
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nest-boilerplate/dist/app
  diff:
    working_directory: ~/nest-boilerplate
    executor: aws-cli/default
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - restore_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Build infra
          command: npm run build:infra
      - run:
          name: Diff
          command: npx cdk diff --all > diff.txt && cat diff.txt

  deployment:
    working_directory: ~/nest-boilerplate
    executor: aws-cli/default
    docker:
      - image: cimg/node:20.12.2-browsers
    steps:
      - restore_cache:
          key: v1-src-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-modules-{{ .Branch }}-{{ checksum "package.json" }}
      - restore_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Build infra
          command: npm run build:infra
      - run:
          name: Deploy
          command: npx cdk deploy --all --require-approval never
workflows:
  version: 2
  full-cycle:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
      - integration_test:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - diff:
          name: diff_to_development
          context: development
          requires:
            - build
            - integration_test
            - unit_test
      - diff:
          name: diff_to_production
          context: production
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build
            - integration_test
            - unit_test
      - approve_deploy_to_development:
          type: approval
          context: development
          filters:
            branches:
              only:
                - master
                - main
                - develop
          requires:
            - diff_to_development
      - approve_deploy_to_production:
          type: approval
          context: production
          requires:
            - diff_to_production
      - deployment:
          name: deployment_to_development
          context: development
          requires:
            - approve_deploy_to_development
      - deployment:
          name: deployment_to_production
          context: production
          requires:
            - approve_deploy_to_production